#!/bin/sh
# PORT OF THE JELLYFIN SERVICE FROM FREEBSD PORTS
. /etc/rc.subr

: ${jellyfin_enable:=NO}
: ${jellyfin_user:="jellyfin"}
: ${jellyfin_group:="jellyfin"}
: ${jellyfin_extraargs:=""}
: ${jellyfin_exec_dir:="/usr/local/jellyfin"}
: ${jellyfin_data_dir:="/var/db/jellyfin"}
: ${jellyfin_cache_dir:="/var/cache/jellyfin"}
: ${jellyfin_pid_dir:="/var/run/jellyfin"}

pidfile="${jellyfin_pid_dir}/${name}_daemon.pid"
pidfile_child="${jellyfin_pid_dir}/${name}_child.pid"

start_precmd=${name}_precmd
jellyfin_precmd() {
    if [ ! -d ${jellyfin_exec_dir} ]; then
        install -d -o ${jellyfin_user} -g ${jellyfin_group} ${jellyfin_exec_dir}
    fi

    if [ ! -d ${jellyfin_data_dir} ]; then
        install -d -o ${jellyfin_user} -g ${jellyfin_group} ${jellyfin_data_dir}
    fi

    if [ ! -d ${jellyfin_cache_dir} ]; then
        install -d -o ${jellyfin_user} -g ${jellyfin_group} ${jellyfin_cache_dir}
    fi

    if [ ! -d ${jellyfin_pid_dir} ]; then
        install -d -o ${jellyfin_user} -g ${jellyfin_group} ${jellyfin_pid_dir}
    fi

    # .NET 6+ use dual mode sockets to avoid the separate AF handling.
    # disable .NET use of V6 if no ipv6 is configured.
    # See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259194#c17
    ifconfig | grep -q inet6
    if [ $? == 1 ]; then
        export DOTNET_SYSTEM_NET_DISABLEIPV6=1
    fi

    rc_flags="-r -f -p ${pidfile_child} -P ${pidfile} ${jellyfin_exec_dir}/jellyfin --datadir ${jellyfin_data_dir} --cachedir ${jellyfin_cache_dir} ${jellyfin_extraargs} >> /dev/null 2>&1 ${rc_flags}"
}

jellyfin_precmd && /usr/local/jellyfin/jellyfin
